name: Python Package using Conda

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file conda_env.yaml --name base
    - name: Compile protobuf
      run: |
        ./compile-protobuf.sh
    - name: type check with mypy
      run: |
        ./type_check.sh
    - name: Test with pytest
      run: |
        py.test -s
