name: pweather-brute-force-ndrank
channels:
  - conda-forge
dependencies:
  - python=3.9.0
  - pyyaml
  - pytest
  - numpy==1.22.4
  - xarray==2022.3.0
  - dask
  - scipy
  - cfgrib
  - cffi
  - cfitsio
  - netcdf4
  - grpcio
  - grpcio-tools
  - grpc-stubs
  - protobuf
  - types-protobuf
  - mypy
  - mypy-protobuf
  - types-pyyaml
  - pandas-stubs
  - schema
  - pandas
  - kafka-python
  - pip
  - pip:
    - BitVector
    - exceptiongroup
