version: '3'
services: 
    cds-downloader:
        build:
            context: .
            dockerfile: ./Dockerfile-cdf-single-requests
        volumes: 
            - ./output:/app/output
            - ./keyfile.json:/app/keyfile.json
            - ./dev-single-requests-properties.yaml:/app/dev-single-requests-properties.yaml
        environment: 
            - GOOGLE_APPLICATION_CREDENTIALS=/app/keyfile.json