name: pweather-resolution-reducer
channels:
  - conda-forge
  - coecms
dependencies:
  - python=3.9.0
  - pyyaml
  - google-cloud-storage
  - google-auth-oauthlib
  - google-api-python-client
  - google-cloud-sdk
  - pytest
  - xarray
  - scipy
  - cfgrib
  - cffi
  - types-pyyaml
  - cfitsio
  - python-cdo
  - netcdf4
  - memory_profiler
  - dask
  - nccompress